name: Assert Tables
description: Asserts the presence of tables in a Deephaven server
inputs:
  table-names:
    description: A string containing a comma separated list of table names to check
    required: true
  host:
    description: The host name or IP address of the Deephaven instance
    required: true
  max-retries:
    description: The maximum attempts to retry connecting to Deephaven
    required: false
    default: 5
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: action-assert-dh-tables-present
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Setup environment
      run: |
        pip install --upgrade pip
        pip install -r ./action-assert-dh-tables-present/assert-tables/requirements.txt
      shell: sh
    - name: Assert tables
      run: python ./action-assert-dh-tables-present/assert-tables/assert_tables.py ${{ inputs.table-names }} ${{ inputs.host }} ${{ inputs.max-retries }}
      shell: sh
